### ISSUE TITLE
Code reproduction

### ISSUE THREAD

**Issue by searchknowledge** [DeepCar/Deepcar5.0#2]
May I ask if your data set is the latest version? After reading your article, I found that the data set category in the article does not match the actual one. In addition, I reviewed the filter code of the headlamp and found that it always fails to meet the expectations,Look forward to receiving your reply, thank you!

**Comment by DeepCar** [comment]
Hello @searchknowledge , Thank you for your interest in our project; It makes us proud!
Some of the images of the datasets were obtained from online traffic cameras, which we were forbidden to share publicly due to copyright issues. The current download links in this repository are before the revision process of the article and the original links were removed from this repository in the past months. We will post an update of the datasets as soon as possible after obtaining the copyright permissions.
If you have any further questions, feel free to ask.

**Comment by searchknowledge** [comment]
I am very glad to receive your letter.In my review of this paper, I adopted the mode of yolov5 architecture in the object detection part. In the training process,the accuracy obtained by each agent into the corresponding classification network was 82.7%、93.81%、90.7% 、74.06% respectively and The accuracy of the test set was 47.48%, 52.4%, 52% and 40% without using filter. I have always failed to reach the corresponding accuracy in the original text. Have you ever had a similar situation in the process of reproduction? In addition, when filter processing the  front light  , it always fails to achieve the result in the original text. May I ask whether the parameters of the front light filter and the uploaded file are the same?In addition, can you provide the weights of the four networks to see what can be achieved with the existing data set.
   Finally,Wish you every success in the future.
